apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-app
  namespace: test
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: prometheus-port
          containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - name: prometheus-port
    protocol: TCP
    port: 9090
    targetPort: prometheus-port
  type: NodePort

